spring.application.name=quizcards
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://quizcard666-instance-1.cryy40480r35.ap-southeast-2.rds.amazonaws.com:3306/quizcards_demo_kien_1?createDatabaseIfNotExist=true
#spring.datasource.username=admin
#spring.datasource.password=KienLeTrung666!)
spring.datasource.url=jdbc:mysql://localhost:3306/quizcards_demo_kien_1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=KiinGoldTRung0112
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.security.user.name=user
spring.security.user.password=leKin123
jwt.secret=zGGwCAroyeB9xnsL8Zco9LcbfkbTEXm15WsLbL7fix31pXWpAS4HjCtEUSxp2dhR
jwt.jwtExpirationInMs=3600000
jwt.refreshTokenExpirationInMs=259200000