spring.application.name=quizcards
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quizcards_demo_kien_1?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=0905775514
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.security.user.name=user
spring.security.user.password=leKin123
jwt.secret=zGGwCAroyeB9xnsL8Zco9LcbfkbTEXm15WsLbL7fix31pXWpAS4HjCtEUSxp2dhR
jwt.jwtExpirationInSec=7200
jwt.refreshTokenExpirationInSec=259200